[build]
target = "riscv64gc-unknown-linux-musl"
[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-unknown-linux-musl-gcc"
# rustflags = [
#     "-C", "target-feature=+xthead,+f,+d,+m,+a,+c,+v"
# ]